Lab6
somov7/m3107-m3108 pull request #153
Opened 2021-12-18 10:45 UTC by SvetaYu

2021-12-18 12:00 UTC, ju5tevg3niy requested changes
LAB6
11

2021-12-18 12:00 UTC, ju5tevg3niy commented on lab6.c
> +    for (int i = 0; i < (sizeFile / 4096); i++)
Буферизация записи
+1

2021-12-28 07:25 UTC, somov7 requested changes
Конечно можно лучше сделать, например, fseek-ом прыгать как только понимаем, что наткнулись не на тот файл в архиве, но в целом +0.5 поставил

2021-12-28 07:25 UTC, somov7 commented on lab6.c
>          char *file = filename;
//codestyle
Вот это вот ваще не понял

2021-12-28 07:25 UTC, somov7 commented on lab6.c
>          char buf[4096];
// codestyle
Такое лучше выносить в константы, сейчас чтоб поменять размер буффера придётся в 11 местах число поменять или типа того

2023-02-02 09:02 UTC, closed without merging