lab 3
somov7/m3107-m3108 pull request #187
Opened 2021-12-30 19:48 UTC by Terrrik

2021-12-30 19:48 UTC, RobinGud commented
10 баллов

2021-12-30 20:10 UTC, RobinGud reviewed
2 лаба 10 баллов(просрок)

2022-01-15 10:26 UTC, somov7 requested changes
-1 за неправильную обработку кодировки (считается, что всегда UTF-8, выводятся кракозяблики и пробелы)
-2 за нерабочий set если нет тега
7

2022-01-15 10:26 UTC, somov7 commented on lab4/utility.h
> +long int get_file_size(FILE* file)
// codestyle
Не надо писать имплементацию функций в .h файле

2022-01-15 10:26 UTC, somov7 commented on lab4/main.c
> +    if (cmp == 4)
// codestyle
лучше strcmp

2022-01-15 10:26 UTC, somov7 commented on lab4/main.c
> +    char* value = malloc(100 * sizeof(char));
//codestyle
magic numbers

2022-01-15 10:26 UTC, somov7 commented on lab4/main.c
> +        if (argv[i][2] == 'f') {
//logical
Неправильно сравнивать флаги только по одной букве

2022-06-30 17:32 UTC, closed without merging