Lab1
somov7/m3107-m3108 pull request #20
Opened 2021-09-21 10:02 UTC by Yuukiine

поставьте 10 пж

2021-09-21 20:05 UTC, somov7 requested changes
Покуда 4.5, программу едва можно назвать рабочей.

2021-09-21 20:05 UTC, somov7 commented on lab1/main.c
> +        else if (arr[i + 1] == ' ') {
// logical
Более того
1) Здесь ты считаешь разделителем только пробел, чуть выше ещё и \t, а ещё выше более-менее все whitespace characters. Надо как сверху.
2) Сверху ты увеличиваешь каунтер слов, когда у тебя начинается слово, а здесь -- когда заканчивается. Отсюда вытекает две баги. Во-первых, ты первое слово подсчитываешь дважды, во-вторых, ты не посчитаешь последнее слово, если после него не идёт пробел. Из-за этого у тебя иногда эти два бага взаимоубивают друг друга на многих примерах. Но это всё ещё два бага.
-1.5

2021-10-09 11:50 UTC, RobinGud commented on lab1/main.c
> +        printf("Error 666. Few arguments.");
Пофиксил.

2021-10-09 11:51 UTC, RobinGud commented on lab1/main.c
> +int main(int argc, char *argv[1]) {
Пофиксил

2021-10-09 11:51 UTC, RobinGud commented on lab1/main.c
> +    Lab1 = fopen(argv[2], "r");
Пофиксил.

2021-10-09 11:56 UTC, RobinGud commented
6 баллов

2021-10-09 11:58 UTC, RobinGud commented
Фейлятся тесты

2025-08-12 00:11 UTC, closed without merging