Lab1
somov7/m3107-m3108 pull request #21
Opened 2021-09-21 13:37 UTC by xvsvg

2021-09-21 13:57 UTC, somov7 reviewed
А зачем ты прошлый пр закрыл и удалил?

2021-09-21 13:59 UTC, xvsvg commented
Я не знаю как у ребят с моей группы получается ловко обращаться с гитом. У
меня не получается и я стараюсь сам разобраться. Сейчас я пр кинул и понял
как это работает

On Tue, 21 Sep 2021 at 16:57, somov7 ***@***.***> wrote:

> ***@***.**** commented on this pull request.
>
> А зачем ты прошлый пр закрыл и удалил?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/somov7/m3107-m3108/pull/21#pullrequestreview-759788149>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVN7NI26GK6HVFHMQPVNNVDUDCFNRANCNFSM5EOPD6PA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-09-21 14:00 UTC, somov7 reviewed
Справа сверху блок Reviewers, когда я ревью закончу, там можно нажать на такой кружочек из двух стрелочек, называется Re-request review

2021-09-21 21:31 UTC, somov7 requested changes
Ставлю 9/10, по логике по мелочи ошибки, программа в целом рабочая. Но от кодстайла конечно глазки текут, если есть возможность не меняя логику программы писать более читабельный код, то стоит так делать (по этой причине тернарники в принципе лучше не стакать).

2021-09-21 21:31 UTC, somov7 commented on WordCount.c
> +        PreviousSym = CurrentSym;
// logical
PreviousSym кажись нигде не используется. После цикла вполне можно использовать CurrentSym
В совокупности с прошлым замечанием -0.5

2021-09-21 21:31 UTC, somov7 commented on WordCount.c
> +                                                                                                                                                              : (Option = -1);
// codestyle
Опять же, тернарники тут только ухудшают читабельность, лучше if'ы

2021-09-21 21:31 UTC, somov7 commented on WordCount.c
> +    int LineState = out;
// logical
Неиспользуемая переменная

2021-09-21 21:31 UTC, somov7 commented on WordCount.c
> +                                                                                                                                                              : (Option = -1);
// logical
Option = -1 не понял зачем (ну видимо чтобы обязательный :-блок в тернарнике заполнить)
-0.5

2021-09-22 05:37 UTC, xvsvg commented
Вы говорили избавиться от ифов и юзать тернарники, я так и сделал. Видимо я
просто не понял, где стоит юзать тернарники, а где ифы. А насчёт codestyle:
я не специально. В предпоследней версии mingw такой стоит по дефолту. Я бы
не использовал тернарники только потому что они форматируются настолько
убого)

On Wed, 22 Sep 2021 at 00:31, somov7 ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Ставлю 9/10, по логике по мелочи ошибки, программа в целом рабочая. Но от
> кодстайла конечно глазки текут, если есть возможность не меняя логику
> программы писать более читабельный код, то стоит так делать (по этой
> причине тернарники в принципе лучше не стакать).
> ------------------------------
>
> In WordCount.c
> <https://github.com/somov7/m3107-m3108/pull/21#discussion_r713383532>:
>
> > +#include <string.h>
>
> +#include <ctype.h>
>
> +#define in 1;
>
> +#define out 0;
>
> +
>
> +long long unsigned fsize(FILE *filename)
>
> +{
>
> +    fseek(filename, 0LLU, SEEK_END);
>
> +    return ftell(filename);
>
> +}
>
> +
>
> +int main(int argc, char *argv[])
>
> +{
>
> +    if (argc != 3)
>
> +    {
>
> +        printf((argc != 1) ? "\nYou've entered %d arguments. But should've entered 3" : "\nYou've entered %d argument. But should've entered 3", argc);
>
>
> //codestyle
> Я вообще имел в виду что-то типа такого. Но уже лучше безусловно.
> ⬇️ Suggested change
>
> -        printf((argc != 1) ? "\nYou've entered %d arguments. But should've entered 3" : "\nYou've entered %d argument. But should've entered 3", argc);
>
> +        printf("\nYou've entered %d argument%s. But should've entered 3", argc, argc == 1 ? "" : "s");
>
>
> ------------------------------
>
> In WordCount.c
> <https://github.com/somov7/m3107-m3108/pull/21#discussion_r713399007>:
>
> > +#include <ctype.h>
>
> +#define in 1;
>
> +#define out 0;
>
> +
>
> +long long unsigned fsize(FILE *filename)
>
> +{
>
> +    fseek(filename, 0LLU, SEEK_END);
>
> +    return ftell(filename);
>
> +}
>
> +
>
> +int main(int argc, char *argv[])
>
> +{
>
> +    if (argc != 3)
>
> +    {
>
> +        printf((argc != 1) ? "\nYou've entered %d arguments. But should've entered 3" : "\nYou've entered %d argument. But should've entered 3", argc);
>
> +        printf("%s%s", "\nUse this template:\nWordCount.exe [Option] filename.(your extension)\nto get started with ->", argv[0]);
>
>
> //codestyle
> Во всех остальных случаях эти %s так и остались.
> ------------------------------
>
> In WordCount.c
> <https://github.com/somov7/m3107-m3108/pull/21#discussion_r713409419>:
>
> > +    ((strcmp(argv[1], "-l") == 0) || (strcmp(argv[1], "--lines") == 0)) ? (Option = 0) : ((strcmp(argv[1], "-c") == 0) || (strcmp(argv[1], "--bytes") == 0)) ? (Option = 1)
>
> +                                                                                     : ((strcmp(argv[1], "-w") == 0) || (strcmp(argv[1], "--words") == 0))   ? (Option = 2)
>
> +                                                                                                                                                             : (Option = -1);
>
>
> // codestyle
> Лучше не стакать тернарники, а через if такое писать
> ------------------------------
>
> In WordCount.c
> <https://github.com/somov7/m3107-m3108/pull/21#discussion_r713427142>:
>
> > +        printf("\n%s", "-w or --words to get the quantity of words\n");
>
> +        return -1;
>
> +    }
>
> +    FILE *filename = fopen(argv[2], "r");
>
> +    if (filename == NULL)
>
> +    {
>
> +        printf("%s", "\nSome kinda error occured during file opening\n1) Check if file exists\n2) Check if file is in the same directory as WordCount.c");
>
> +        return -1;
>
> +    }
>
> +    unsigned long long WordCounter = 0, LineCounter = 0;
>
> +    char CurrentSym, PreviousSym = '\0';
>
> +    int WordState = out;
>
> +    int LineState = out;
>
> +    while ((CurrentSym = getc(filename)) != EOF)
>
> +    {
>
> +        PreviousSym = CurrentSym;
>
>
> // logical
> PreviousSym кажись нигде не используется. После цикла вполне можно
> использовать CurrentSym
> В совокупности с прошлым замечанием -0.5
> ------------------------------
>
> In WordCount.c
> <https://github.com/somov7/m3107-m3108/pull/21#discussion_r713428483>:
>
> > +    (Option == 0) ? printf("\nThe quantity of lines is: %llu \nthanks for using!\n\nMade by Oleinikov Vladimir on 13.09.2021\n", LineCounter) : (Option == 1) ? printf("\nThe file size is: %llu bytes\nthanks for using!\n\nMade by Oleinikov Vladimir on 13.09.2021\n", fsize(filename))
>
> +                                                                                                                                            : (Option == 2)   ? printf("\nThe quantity of words is: %llu \nthanks for using!\n\nMade by Oleinikov Vladimir on 13.09.2021\n", WordCounter)
>
> +                                                                                                                                                              : (Option = -1);
>
>
> // codestyle
> Опять же, тернарники тут только ухудшают читабельность, лучше if'ы
> ------------------------------
>
> In WordCount.c
> <https://github.com/somov7/m3107-m3108/pull/21#discussion_r713428778>:
>
> > +    {
>
> +        printf("\n%s", "Option doesn't exist. Use that list of available commands:\n-l or --lines to get lines quantity only");
>
> +        printf("\n%s", "-c or --bytes to get size of file in bytes");
>
> +        printf("\n%s", "-w or --words to get the quantity of words\n");
>
> +        return -1;
>
> +    }
>
> +    FILE *filename = fopen(argv[2], "r");
>
> +    if (filename == NULL)
>
> +    {
>
> +        printf("%s", "\nSome kinda error occured during file opening\n1) Check if file exists\n2) Check if file is in the same directory as WordCount.c");
>
> +        return -1;
>
> +    }
>
> +    unsigned long long WordCounter = 0, LineCounter = 0;
>
> +    char CurrentSym, PreviousSym = '\0';
>
> +    int WordState = out;
>
> +    int LineState = out;
>
>
> // logical
> Неиспользуемая переменная
> ------------------------------
>
> In WordCount.c
> <https://github.com/somov7/m3107-m3108/pull/21#discussion_r713431626>:
>
> > +    (Option == 0) ? printf("\nThe quantity of lines is: %llu \nthanks for using!\n\nMade by Oleinikov Vladimir on 13.09.2021\n", LineCounter) : (Option == 1) ? printf("\nThe file size is: %llu bytes\nthanks for using!\n\nMade by Oleinikov Vladimir on 13.09.2021\n", fsize(filename))
>
> +                                                                                                                                            : (Option == 2)   ? printf("\nThe quantity of words is: %llu \nthanks for using!\n\nMade by Oleinikov Vladimir on 13.09.2021\n", WordCounter)
>
> +                                                                                                                                                              : (Option = -1);
>
>
> // logical
> Option = -1 не понял зачем (ну видимо чтобы обязательный :-блок в
> тернарнике заполнить)
> -0.5
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/somov7/m3107-m3108/pull/21#pullrequestreview-760206850>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVN7NIYOQVKKRJGSCBSHSVDUDD2SXANCNFSM5EOPD6PA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-09-22 07:40 UTC, somov7 reviewed
Я писал про тернарники внутри if-а в одном конкретном месте и про большое количество дублирования. В любом случае я не снижал за кодстайл. 
Предполагалось, что ты напишешь что-то типа:
```
char *OptionName[3] = {"quantity of lines", "file size", "quantity of words"};
unsigned long long Result[3] = {LineCounter, fsize(filename), WordCounter};
printf("\nThe %s is: %llu\nthanks for using!\n\nMade by Oleinikov Vladimir on 13.09.2021", OptionName[Option], Result[Option]);
fclose(filename);
return 0;
```

2021-09-22 18:28 UTC, xvsvg commented on WordCount.c
> +        PreviousSym = CurrentSym;
PreviousSym используется после цикла. Смысл PreviousSym проверить, чем закончилась предыдущая строка, тк возможны случаи:
1)....EOF
2)'\n'
EOF
В обоих случаях CurrentSym по окончании цикла будет иметь значение EOF.

2021-09-22 18:49 UTC, closed without merging