Lab1
somov7/m3107-m3108 pull request #4
Opened 2021-09-18 11:05 UTC by gost3228

2021-09-18 11:15 UTC, somov7 requested changes
9/10

2021-09-18 11:15 UTC, somov7 commented on lab1/main.c
> +    int words_count = 0, lines_count = 0, characters_count = 0, n = 256, ch, reading_word = 0;
Что такое n?

2021-09-18 11:15 UTC, somov7 commented on lab1/main.c
> +    return 1;
)

2021-09-18 11:15 UTC, somov7 commented on lab1/main.c
> +                cli_args.show_words = true;
Эта штука никак не обрабатывает неправильные флаги

2021-09-18 11:15 UTC, somov7 commented on lab1/main.c
> +            if (strcmp(argv[i], "--bytes") == 0 || strcmp(argv[i], "-c") == 0) {
else

2021-09-19 21:51 UTC, somov7 requested changes
Прогнал тесты:
1) Всегда выводит на 1 строку меньше, чем нужно
2) Неправильно обрабатывает случай, когда передан некорректный аргумент (не возвращает код ошибки)
8/10

2021-09-20 06:50 UTC, gost3228 commented
Я сравнил подсчет строк у себя и в утилите wc (линукс), все совпадает.

2021-09-20 07:09 UTC, somov7 commented
> Я сравнил подсчет строк у себя и в утилите wc (линукс), все совпадает.

Если ты откроешь документацию по wc, там сказано, что он считает количество \n. В лабораторной сказано посчитать количество строк.

2021-09-28 19:13 UTC, somov7 requested changes
Выглядит рабочим, поставил 10

2021-09-28 19:13 UTC, somov7 commented on lab1/main.c
> +    Counts counts = count_data(fp);;
// codestyle
;;

2025-07-22 13:43 UTC, closed without merging