lab3
somov7/m3107-m3108 pull request #79
Opened 2021-11-06 10:58 UTC by SvetaYu

Юдина Светлана

2021-11-06 11:45 UTC, somov7 requested changes
10

2021-11-06 11:45 UTC, somov7 commented on new3.c
> +int strtoint(char *month)
// codestyle
Это восхитительно

2021-11-06 11:45 UTC, somov7 commented on new3.c
> +    time->tm_sec = (fgetc(fin) - 48) * 10 + fgetc(fin) - 48;
// codestyle
atoi

2021-11-06 11:45 UTC, somov7 commented on new3.c
> +        if ((symbol != '1') && (symbol != '2'))
// logical
Нужно вывести 5xx-ошибки

2021-11-20 12:25 UTC, SvetaYu commented
lab4

2021-11-20 13:04 UTC, somov7 requested changes
10

2023-02-02 09:02 UTC, closed without merging