Add files via upload
somov7/m3107-m3108 pull request #9
Opened 2021-09-18 11:36 UTC by xvsvg

2021-09-18 12:07 UTC, somov7 requested changes
8/10

2021-09-18 12:07 UTC, somov7 commented on WordCount.c
> +        if (CurrentSym == ' ' || CurrentSym == ',' || CurrentSym == '.' || CurrentSym == '!' || CurrentSym == '?' || CurrentSym == '\n' || CurrentSym == EOF)
Считаем все знаки препинания частью слова. Считаем whitespace characters разделителями слов

2021-09-18 12:07 UTC, somov7 commented on WordCount.c
> +            LineState = in;
Пустые строки тоже строки

2021-09-18 14:34 UTC, xvsvg commented
[image: image.png]
ничего не менял,сразу запустил. я не понимаю о чем идет речь искренне, для
меня — работа на полный балл.

сб, 18 сент. 2021 г. в 15:07, somov7 ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> 8/10
> ------------------------------
>
> In WordCount.c
> <https://github.com/somov7/m3107-m3108/pull/9#discussion_r711580818>:
>
> > +#include <ctype.h>
>
> +#define in 1;
>
> +#define out 0;
>
> +
>
> +int fsize(FILE *filename)
>
> +{
>
> +    fseek(filename, 0LLU, SEEK_END);
>
> +    return ftell(filename);
>
> +}
>
> +
>
> +int main(int argc, char *argv[])
>
> +{
>
> +    if (argc != 3)
>
> +    {
>
> +        if (argc != 1)
>
> +            printf("%s%d%s", "\nYou've entered ", argc, " arguments. But should've entered 3");
>
>
> Зачем передавать литералы через %s, напиши сразу printf("You've entered %d
> ...", argc)
> ------------------------------
>
> In WordCount.c
> <https://github.com/somov7/m3107-m3108/pull/9#discussion_r711581052>:
>
> > +        printf("\n%s", "[-w] or [--words] to get the quantity of words\n");
>
> +        return -1;
>
> +    }
>
> +    FILE *filename = fopen(argv[2], "r");
>
> +    if (filename == NULL)
>
> +    {
>
> +        printf("%s", "\nSome kinda error occured during file opening\n1) Check if file exists\n2) Check if file is in the same directory as WordCount.c");
>
> +        return -1;
>
> +    }
>
> +    unsigned long long WordCounter = 0, LineCounter = 0;
>
> +    char CurrentSym;
>
> +    int WordState = out;
>
> +    int LineState = out;
>
> +    while ((CurrentSym = getc(filename)) != EOF)
>
> +    {
>
> +        if (CurrentSym == ' ' || CurrentSym == ',' || CurrentSym == '.' || CurrentSym == '!' || CurrentSym == '?' || CurrentSym == '\n' || CurrentSym == EOF)
>
>
> Считаем все знаки препинания частью слова. Считаем whitespace characters
> разделителями слов
> ------------------------------
>
> In WordCount.c
> <https://github.com/somov7/m3107-m3108/pull/9#discussion_r711581667>:
>
> > +        if (CurrentSym == '\n' || CurrentSym == EOF)
>
> +        {
>
> +            LineState = out;
>
> +        }
>
> +        else if (LineState == 0)
>
> +        {
>
> +            LineCounter++;
>
> +            LineState = in;
>
>
> Пустые строки тоже строки
> ------------------------------
>
> In WordCount.c
> <https://github.com/somov7/m3107-m3108/pull/9#discussion_r711580850>:
>
> > +#include <ctype.h>
>
> +#define in 1;
>
> +#define out 0;
>
> +
>
> +int fsize(FILE *filename)
>
> +{
>
> +    fseek(filename, 0LLU, SEEK_END);
>
> +    return ftell(filename);
>
> +}
>
> +
>
> +int main(int argc, char *argv[])
>
> +{
>
> +    if (argc != 3)
>
> +    {
>
> +        if (argc != 1)
>
> +            printf("%s%d%s", "\nYou've entered ", argc, " arguments. But should've entered 3");
>
>
> Касается всех мест если что
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/somov7/m3107-m3108/pull/9#pullrequestreview-758056521>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVN7NI42MANAAHG4WEYVNNLUCR6JRANCNFSM5EJDZG4Q>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-09-19 21:45 UTC, somov7 requested changes
Ещё раз глянул, ещё пару косяков заметил, тесты тоже не все прошло. 6/10.

2021-09-19 21:45 UTC, somov7 commented on WordCount.c
> +        printf("%s%llu\n%s", "\nThe quantity of lines is: ", LineCounter, "thanks for using!\n\nMade by Oleinikov Vladimir on 13.09.2021");
Нельзя выводить int через %llu, он выводит не то, что ты ожидаешь

2021-09-19 21:45 UTC, somov7 commented on WordCount.c
> +    if (strcmp(argv[1], "[-l]") == 0 || strcmp(argv[1], "[--lines]") == 0)
Аргументы должны без квадратных скобочек идти.

2021-09-19 21:45 UTC, somov7 commented on WordCount.c
> +            printf("%s%d%s", "\nYou've entered ", argc, " arguments. But should've entered 3");
И да, попробуй это через тернарник в принтфе сделать, а не плодить две почти одинаковые строки почти.

2021-09-19 21:45 UTC, somov7 commented on WordCount.c
> +        return 0;
У тебя три if-блока почти одинаковых, попробуй от такого количества дублирования избавиться

2021-09-21 11:57 UTC, closed without merging